public class Music
{
    //JFUGUE
    private MusicSettings settings;
    private String text;
    private Pattern[] music_generator; // PATTERN IS A JFUGUE CLASS

    public Music(MusicSettings settings, String text)
    {
        this.settings = settings;
        this.text = text;
    }

    public void generate()
    {
        // TODO
        // GENERATE A MUSIC PERSONALIZED BY THE USER AS A LIST OF PATTERNS (OF JFUGUE LIBRARY)

    }
    public void save(String path)
    {
        // TODO
        // SAVE THE MUSIC GENERATED BY THE USER IN THE PATH PARAMETER
    }

    public String getText()
    {

        return this.text;
    }
    public void setText(String text)
    {

        this.text = text;
    }

    public MusicSettings getSettings()
    {
        return this.settings;
    }
    public void setSettings(MusicSettings settings)
    {

        this.settings = settings;
    }

    public Pattern[] getPattern() {

        return this.music_generator;
    }
}
