package com.example.projeto_tcp;

import org.jfugue.pattern.Pattern;

import java.util.Random;
import java.util.Scanner;

public class Music
{
    //JFUGUE
    private MusicSettings defaultSettings;
    private MusicSettings settings;
    private String text;
    private Pattern music_generator; // PATTERN IS A JFUGUE CLASS


    public Music(MusicSettings settings, String text)
    {
        this.defaultSettings = new MusicSettings(settings.getBpm(),settings.getTimbre(),settings.getInstrument(),settings.getVolume());
        this.settings = new MusicSettings(settings.getBpm(),settings.getTimbre(),settings.getInstrument(),settings.getVolume());
        this.text = text;
    }

    public void generate()
    {
        String patternText = setVolumePattern()+setBPMPattern()+setInstrumentPattern();
        for (int i = 0; i < text.length(); i++) {
            String newSymbol = mapping(text.charAt(i) ,i);
            if (newSymbol.equals("BPM+")){
                i+=3;
                patternText+=setBPMPattern();
            } else if (newSymbol.equals("BPM-")) {
                patternText+=setBPMPattern();
            } else if (newSymbol.equals("V")) {
                patternText+=setVolumePattern();
            } else if (newSymbol.equals("T")) {
                patternText+="I[Telephone_Ring] A ";
                patternText+=setInstrumentPattern();
            } else {
                patternText+=newSymbol;
            }

        }
        Pattern newPattern = new Pattern(patternText);
        music_generator =  newPattern;
    }

    public String mapping(char character, int index)
    {
        character = Character.toUpperCase(character);
        switch (character){
            case ('B'):
                if (text.length() >= index+4 && text.substring(index+1, index+4).equals("PM+")){
                    getSettings().setBpm(getSettings().getBpm()+80);
                    return "BPM+";
                } else if (text.length() >= index+4 && text.substring(index+1, index+4).equals("PM-")) {
                    getSettings().setBpm(getSettings().getBpm()-80);
                    return "BPM+";
                } else {
                    return Character.toString(character)+" ";
                }
            case('A'):
            case('C'):
            case('D'):
            case('E'):
            case('F'):
            case('G'):
                return Character.toString(character)+" ";
            case('+'):
                if (getSettings().getVolume()*2 > 127){
                    getSettings().setVolume(127);
                } else{
                    getSettings().setVolume(getSettings().getVolume()*2);
                }
                return "V";
            case('-'):
                getSettings().setVolume(getDefaultSettings().getVolume());
                return "V";
            case(' '):
                return "R ";
            case('?'):
                Random random = new Random();
                int indiceSorteado = random.nextInt(Symbol.G.getAsciiValue() - Symbol.A.getAsciiValue() +1);
                return Character.toString((char) (Symbol.A.getAsciiValue()+indiceSorteado))+" ";
            case('O'):
            case('I'):
            case('U'):
                char prevChar = Character.toUpperCase(text.charAt(index-1));
                if (prevChar >= Symbol.A.getAsciiValue() && prevChar <= Symbol.G.getAsciiValue()){
                    return Character.toString(prevChar)+" ";
                } else {
                    return "T";
                }
            case(';'):
                random = new Random();
                indiceSorteado = random.nextInt(400);
                getSettings().setBpm(indiceSorteado);
                return "BPM-";
        }
        return "";
    }
    public void save(String path)
    {
        // TODO
        // SAVE THE MUSIC GENERATED BY THE USER IN THE PATH PARAMETER
    }

    public String getText()
    {
        return this.text;
    }
    public void setText(String text)
    {
        this.text = text;
    }

    public MusicSettings getSettings()
    {
        return this.settings;
    }
    public void setSettings(MusicSettings settings)
    {

        this.settings = settings;
    }

    public MusicSettings getDefaultSettings() {
        return defaultSettings;
    }

    public Pattern getPattern() {
        return this.music_generator;
    }

    public String setVolumePattern(){
        return ":CON(7, "+ Integer.toString(getSettings().getVolume()) +") ";
    }

    public String setBPMPattern(){
        return "T"+ Integer.toString(getSettings().getBpm()) +" ";
    }

    public String setInstrumentPattern(){
        return "I["+ getSettings().getInstrument() +"] ";
    }
}
